### ISSUE TITLE
Can you provide deblurred GT image in raw format?

### ISSUE THREAD

**Issue by jakeyoo87** [cmu-ci-lab/dual_pixel_defocus_estimation_deblurring#1]
Hello, thank you for the great work.
It seems like the dataset in this repository is in raw format, 
different from the images in https://imaging.cs.cmu.edu/dual_pixels/supplement/001/index.html.

After running the code, how do we compare it with the groundtruth deblurred image (which is not in raw format). Do you apply gamma correction??

Thank you.

**Comment by erfect2020** [comment]
Same issue, have you got a solution?

**Comment by shumianxin** [comment]
Hi, I just uploaded two folders containing the ground truth under the ./DP_data_pixel_4 directory. The GT all-in-focus images are raw images without tone mapping. 

Images on this webpage (https://imaging.cs.cmu.edu/dual_pixels/supplement/001/index.html) are for visualization purposes, and are tone mapped. 

Let me know if it resolves the problem.
