### ISSUE TITLE
Questions of the GT images

### ISSUE THREAD

**Issue by erfect2020** [cmu-ci-lab/dual_pixel_defocus_estimation_deblurring#2]
The values of GT images exceeds the 2^14  and does not match the values of raw inputs. How should I use the pre-processed GT?

**Comment by erfect2020** [comment]
I think the GTs are intermediate results. Could you provide the corresponding pre-processed left/right images?

**Comment by shumianxin** [comment]
They are rescaled to 16-bit data, so normalize by (2^16-1) should work.

**Comment by erfect2020** [comment]
When I normalize GTs by (2^16-1), the maximum value of GT is around 0.5 instead of 1. I do not think that is friendly to someone who just want to evaluate comparison methods on this dataset.

**Comment by shumianxin** [comment]
In L30-31 & L63-64 of ./run.py, we first normalize the data to [0, 1], and then undo the normalization. It is also explained in the supplementary material Sec. 4. This way, we can handle data of various dynamic ranges.
