### ISSUE TITLE
Question Regarding the Calibration

### ISSUE THREAD

**Issue by TouqeerAhmad** [cmu-ci-lab/dual_pixel_defocus_estimation_deblurring#3]
Hi, I am a bit confused about the 2 Hour reported time of the optimization in paper and the readme: 
"Each optimization runs for 10,000 iterations with an Adam optimizer, and takes about 2 hours on an Nvidia Titan RTX GPU."

Does that mean for each DP pair, if one wants to get a defocus-map, one has to run the optimization for 2 hours? Or this could be done once for a Pixel device using the calibration pattern of discs, and then the inference should be very quick given the DP pair and original kernels? 

Thanks, 
Touqeer

**Comment by shumianxin** [comment]
Hi @TouqeerAhmad, the former interpretation is correct---for each DP pair, if one wants to get a defocus-map, one has to run the optimization for 2 hours. The one-time calibration is a prerequisite for obtaining the kernels, and does not affect the inference time.
